package core

import (
	"html"
	"regexp"
	"strings"
)

// renderMarkdown converts a subset of CommonMark / GitHub-flavored markdown to
// HTML safe for injection via g.Raw(...). It is deliberately minimal: it
// supports the constructs we observe in platform "rules" payloads —
// headings, unordered/ordered lists, GFM pipe tables, fenced code blocks,
// blockquotes, horizontal rules, paragraphs, and the inline spans **bold**,
// *italic*, `code`, and [text](url).
//
// Security: the input is HTML-escaped up-front, then ONLY tags generated by
// this renderer appear in the output. There is no path by which raw `<script>`
// or `<a onclick=...>` from the platform can reach the response — they are
// escaped to `&lt;script&gt;` etc. before any markdown transformation runs.
//
// This is intentionally not a full CommonMark implementation; if a future
// program rules payload uses exotic syntax, it will degrade to a paragraph
// rather than fail. The trade-off is keeping the code small and dependency-free
// (the project does not allow new top-level deps without strong justification).
func renderMarkdown(src string) string {
	if src == "" {
		return ""
	}
	// Escape first — all subsequent replacements are our own generated tags.
	escaped := html.EscapeString(src)

	lines := strings.Split(escaped, "\n")
	var out strings.Builder
	i := 0
	for i < len(lines) {
		line := lines[i]

		// Blank line — paragraph separator.
		if strings.TrimSpace(line) == "" {
			i++
			continue
		}

		// Fenced code block: ``` ... ```
		if strings.HasPrefix(strings.TrimSpace(line), "```") {
			lang := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "```"))
			_ = lang // language hint unused for now; client-side highlighting can pick it up via class
			i++
			var code strings.Builder
			for i < len(lines) && !strings.HasPrefix(strings.TrimSpace(lines[i]), "```") {
				code.WriteString(lines[i])
				code.WriteByte('\n')
				i++
			}
			if i < len(lines) {
				i++ // consume closing fence
			}
			out.WriteString(`<pre class="bg-zinc-900/50 border border-zinc-700/40 rounded-lg p-3 my-2 overflow-x-auto text-sm text-zinc-300"><code>`)
			out.WriteString(strings.TrimSpace(code.String()))
			out.WriteString(`</code></pre>`)
			out.WriteByte('\n')
			continue
		}

		// ATX heading: # .. ######
		if h, level := parseHeading(line); level > 0 {
			out.WriteString(`<h`)
			out.WriteString(itoa(level))
			out.WriteString(` class="text-zinc-200 font-semibold mt-4 mb-2">`)
			out.WriteString(renderInline(h))
			out.WriteString(`</h`)
			out.WriteString(itoa(level))
			out.WriteString(`>`)
			out.WriteByte('\n')
			i++
			continue
		}

		// Horizontal rule: --- *** ___ (3+ same chars on a line by itself)
		if isHR(line) {
			out.WriteString(`<hr class="border-zinc-700/50 my-4">` + "\n")
			i++
			continue
		}

		// GFM pipe table: a header row + a separator row + body rows.
		if isTableRow(line) && i+1 < len(lines) && isTableSeparatorRow(lines[i+1]) {
			consumed := renderTable(lines[i:], &out)
			i += consumed
			continue
		}

		// Blockquote: > text
		if strings.HasPrefix(strings.TrimSpace(line), "&gt;") || strings.HasPrefix(strings.TrimSpace(line), ">") {
			var bq strings.Builder
			for i < len(lines) {
				l := lines[i]
				t := strings.TrimSpace(l)
				if t == "" {
					break
				}
				if strings.HasPrefix(t, "&gt;") {
					bq.WriteString(strings.TrimSpace(strings.TrimPrefix(t, "&gt;")))
				} else if strings.HasPrefix(t, ">") {
					bq.WriteString(strings.TrimSpace(strings.TrimPrefix(t, ">")))
				} else {
					break
				}
				bq.WriteByte('\n')
				i++
			}
			out.WriteString(`<blockquote class="border-l-2 border-zinc-600 pl-3 my-2 text-zinc-400 text-sm">`)
			out.WriteString(renderInline(bq.String()))
			out.WriteString(`</blockquote>`)
			out.WriteByte('\n')
			continue
		}

		// List: consecutive lines starting with - / * / + (unordered) or N. (ordered).
		if isUnorderedListItem(line) || isOrderedListItem(line) {
			consumed := renderList(lines[i:], &out)
			i += consumed
			continue
		}

		// Default: paragraph — collect until blank line or block starter.
		var para strings.Builder
		for i < len(lines) {
			l := lines[i]
			if strings.TrimSpace(l) == "" {
				break
			}
			if isBlockStart(l, lines, i) {
				break
			}
			para.WriteString(l)
			para.WriteByte(' ')
			i++
		}
		text := strings.TrimSpace(para.String())
		if text != "" {
			out.WriteString(`<p class="text-zinc-300 text-sm leading-relaxed my-2">`)
			out.WriteString(renderInline(text))
			out.WriteString(`</p>`)
			out.WriteByte('\n')
		}
	}
	return out.String()
}

// isBlockStart reports whether the current line begins a different block
// (heading / hr / table / list / code fence / blockquote), used by paragraph
// collection to know when to stop absorbing lines.
func isBlockStart(line string, lines []string, idx int) bool {
	if _, lvl := parseHeading(line); lvl > 0 {
		return true
	}
	if isHR(line) {
		return true
	}
	if strings.HasPrefix(strings.TrimSpace(line), "```") {
		return true
	}
	if isUnorderedListItem(line) || isOrderedListItem(line) {
		return true
	}
	if isTableRow(line) && idx+1 < len(lines) && isTableSeparatorRow(lines[idx+1]) {
		return true
	}
	if strings.HasPrefix(strings.TrimSpace(line), "&gt;") || strings.HasPrefix(strings.TrimSpace(line), ">") {
		return true
	}
	return false
}

// parseHeading returns the heading text and its level (1-6) for ATX-style
// headings like "## Title". Returns ("", 0) if the line is not a heading.
func parseHeading(line string) (string, int) {
	t := strings.TrimSpace(line)
	level := 0
	for level < len(t) && t[level] == '#' {
		level++
	}
	if level == 0 || level > 6 {
		return "", 0
	}
	if level >= len(t) || t[level] != ' ' {
		return "", 0
	}
	return strings.TrimSpace(t[level+1:]), level
}

// isHR reports whether the line is a horizontal rule (3+ of - * _ only).
func isHR(line string) bool {
	t := strings.TrimSpace(line)
	if len(t) < 3 {
		return false
	}
	c := t[0]
	if c != '-' && c != '*' && c != '_' {
		return false
	}
	for i := 1; i < len(t); i++ {
		if t[i] != c && t[i] != ' ' {
			return false
		}
	}
	// Must contain at least 3 of the marker char.
	count := 0
	for i := 0; i < len(t); i++ {
		if t[i] == c {
			count++
		}
	}
	return count >= 3
}

// isTableRow reports whether a line looks like a markdown table row:
// starts and ends with a pipe (after trimming whitespace).
func isTableRow(line string) bool {
	t := strings.TrimSpace(line)
	if len(t) < 2 {
		return false
	}
	return strings.HasPrefix(t, "|") && strings.HasSuffix(t, "|") && strings.Contains(t, "|")
}

// isTableSeparatorRow reports whether a line is a markdown table separator
// like "| --- | --- |" (cells are dashes/colons only).
func isTableSeparatorRow(line string) bool {
	t := strings.TrimSpace(line)
	t = strings.TrimPrefix(t, "|")
	t = strings.TrimSuffix(t, "|")
	cells := strings.Split(t, "|")
	if len(cells) == 0 {
		return false
	}
	for _, c := range cells {
		c = strings.TrimSpace(c)
		if c == "" {
			return false
		}
		for j := 0; j < len(c); j++ {
			ch := c[j]
			if ch != '-' && ch != ':' && ch != ' ' {
				return false
			}
		}
		// Must contain at least one dash.
		if !strings.Contains(c, "-") {
			return false
		}
	}
	return true
}

// renderTable writes the HTML for a markdown table starting at lines[0]. The
// header is lines[0], the separator is lines[1] (already verified by the
// caller), body rows are subsequent lines that still match isTableRow.
// Returns the number of input lines consumed.
func renderTable(lines []string, out *strings.Builder) int {
	if len(lines) < 2 {
		return 0
	}
	out.WriteString(`<div class="overflow-x-auto my-3"><table class="min-w-full border border-zinc-700/40 rounded-lg text-sm">`)

	// Header.
	header := splitTableRow(lines[0])
	out.WriteString(`<thead class="bg-zinc-800/50"><tr>`)
	for _, h := range header {
		out.WriteString(`<th class="px-3 py-2 text-left text-xs font-semibold text-zinc-300 uppercase tracking-wider border-b border-zinc-700/50">`)
		out.WriteString(renderInline(h))
		out.WriteString(`</th>`)
	}
	out.WriteString(`</tr></thead>`)

	// Body.
	out.WriteString(`<tbody class="divide-y divide-zinc-700/40">`)
	consumed := 2
	for i := 2; i < len(lines); i++ {
		if !isTableRow(lines[i]) {
			break
		}
		cells := splitTableRow(lines[i])
		out.WriteString(`<tr>`)
		for ci, c := range cells {
			tag := "td"
			if ci == 0 {
				tag = `td class="px-3 py-2 text-zinc-200 font-medium"`
			} else {
				tag = `td class="px-3 py-2 text-zinc-400"`
			}
			out.WriteString(`<`)
			out.WriteString(tag)
			out.WriteString(`>`)
			out.WriteString(renderInline(c))
			out.WriteString(`</`)
			out.WriteString(strings.SplitN(tag, " ", 2)[0])
			out.WriteString(`>`)
		}
		out.WriteString(`</tr>`)
		consumed++
	}
	out.WriteString(`</tbody></table></div>`)
	out.WriteByte('\n')
	return consumed
}

// splitTableRow splits "| a | b | c |" into ["a", "b", "c"], trimming each cell.
func splitTableRow(row string) []string {
	t := strings.TrimSpace(row)
	t = strings.TrimPrefix(t, "|")
	t = strings.TrimSuffix(t, "|")
	parts := strings.Split(t, "|")
	out := make([]string, len(parts))
	for i, p := range parts {
		out[i] = strings.TrimSpace(p)
	}
	return out
}

// isUnorderedListItem reports whether the line starts an unordered list item.
func isUnorderedListItem(line string) bool {
	t := strings.TrimSpace(line)
	if len(t) < 3 {
		return false
	}
	return (strings.HasPrefix(t, "- ") || strings.HasPrefix(t, "* ") || strings.HasPrefix(t, "+ "))
}

// isOrderedListItem reports whether the line starts an ordered list item.
func isOrderedListItem(line string) bool {
	t := strings.TrimSpace(line)
	if len(t) < 3 {
		return false
	}
	i := 0
	for i < len(t) && t[i] >= '0' && t[i] <= '9' {
		i++
	}
	if i == 0 {
		return false
	}
	return i+1 < len(t) && t[i] == '.' && t[i+1] == ' '
}

// renderList writes the HTML for a list starting at lines[0]. Returns the
// number of lines consumed.
func renderList(lines []string, out *strings.Builder) int {
	ordered := isOrderedListItem(lines[0])
	listTag := "ul"
	if ordered {
		listTag = "ol"
	}
	out.WriteString(`<`)
	out.WriteString(listTag)
	out.WriteString(` class="list-disc ml-6 my-2 space-y-1 text-zinc-300 text-sm">`)
	if ordered {
		// Override class for ordered lists.
		out.Reset()
		out.WriteString(`<ol class="list-decimal ml-6 my-2 space-y-1 text-zinc-300 text-sm">`)
	}
	consumed := 0
	for i := 0; i < len(lines); i++ {
		l := lines[i]
		t := strings.TrimSpace(l)
		if t == "" {
			break
		}
		if !isUnorderedListItem(l) && !isOrderedListItem(l) {
			break
		}
		// Strip the leading marker (- / * / + / N.).
		var content string
		if isUnorderedListItem(l) {
			content = strings.TrimSpace(t[2:])
		} else {
			// Skip past the digits and ". ".
			j := 0
			for j < len(t) && t[j] >= '0' && t[j] <= '9' {
				j++
			}
			content = strings.TrimSpace(t[j+2:])
		}
		// Continuation: subsequent indented non-list lines belong to this item.
		// We collapse them into the same <li> as a paragraph.
		out.WriteString(`<li class="leading-relaxed">`)
		out.WriteString(renderInline(content))
		// Look ahead for continuation lines (indented text that isn't a new list
		// item or block start).
		for i+1 < len(lines) {
			next := lines[i+1]
			nt := strings.TrimSpace(next)
			if nt == "" || isUnorderedListItem(next) || isOrderedListItem(next) || isBlockStart(next, lines, i+1) {
				break
			}
			if strings.HasPrefix(next, "    ") || strings.HasPrefix(next, "\t") {
				out.WriteString(`<br>`)
				out.WriteString(renderInline(strings.TrimSpace(next)))
				i++
			} else {
				break
			}
		}
		out.WriteString(`</li>`)
		consumed++
	}
	out.WriteString(`</`)
	out.WriteString(listTag)
	out.WriteString(`>`)
	out.WriteByte('\n')
	return consumed
}

// Inline patterns. Compiled once at package init.
var (
	inlineBoldRegex   = regexp.MustCompile(`\*\*([^*]+)\*\*`)
	inlineItalicRegex = regexp.MustCompile(`\*([^*]+)\*`)
	inlineCodeRegex   = regexp.MustCompile("`([^`]+)`")
	inlineLinkRegex   = regexp.MustCompile(`\[([^\]]+)\]\(([^)]+)\)`)
)

// renderInline renders inline markdown (bold, italic, code, links) into HTML.
// The input is assumed already HTML-escaped at the document level.
func renderInline(s string) string {
	// Links first — they may contain their own marker characters.
	s = inlineLinkRegex.ReplaceAllStringFunc(s, func(m string) string {
		sub := inlineLinkRegex.FindStringSubmatch(m)
		if len(sub) < 3 || sub[2] == "" {
			return m
		}
		text := sub[1]
		url := sub[2]
		// Reject javascript: / data: URLs defensively (input is escaped, but
		// a program could still embed a literal "javascript:..." string).
		lu := strings.ToLower(url)
		if strings.HasPrefix(lu, "javascript:") || strings.HasPrefix(lu, "data:") {
			return text
		}
		return `<a href="` + url + `" target="_blank" rel="noopener noreferrer" class="text-cyan-400 hover:text-cyan-300">` + text + `</a>`
	})
	s = inlineCodeRegex.ReplaceAllString(s, `<code class="bg-zinc-900/60 border border-zinc-700/40 rounded px-1 py-0.5 text-xs text-zinc-300">$1</code>`)
	s = inlineBoldRegex.ReplaceAllString(s, `<strong class="font-semibold text-zinc-200">$1</strong>`)
	s = inlineItalicRegex.ReplaceAllString(s, `<em class="italic">$1</em>`)
	return s
}

// itoa is a tiny local int→string helper to avoid importing strconv just for
// one call site.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	if neg {
		b = append([]byte{'-'}, b...)
	}
	return string(b)
}
